version: "3.7"

services:
  # database
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blog-db
    volumes:
      - pgdata:/data/postgres

  # the app we are building
  blog-api:
    build: .
    container_name: blog-api
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ".:/usr/app"
    links:
      - postgres
    depends_on:
      - postgres

  # For Email trapping
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025

  # For rate limiting
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
